#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EFApproaches;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h1>Contoso University from another PC</h1>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(@">
        <h2>Welcome to Contoso University</h2>
        <p>
            Contoso University is a sample application that
            demonstrates how to use Entity Framework 6 in an
            ASP.NET MVC 5 web application.
        </p>
    </div>
    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Build it from scratch</h2>\r\n        <p>You can build the applicati" +
"on by following the steps in the tutorial series on the ASP.NET site.</p>\r\n     " +
"   <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://www.asp.net/mvc/tutorials/getting-started-with-ef-using-mvc/\"");

WriteLiteral(">See the tutorial &raquo;</a></p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Download it</h2>\r\n        <p>You can download the completed projec" +
"t from the Microsoft Code Gallery.</p>\r\n        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://code.msdn.microsoft.com/ASPNET-MVC-Application-b01a9fe8\"");

WriteLiteral(">Download &raquo;</a></p>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
