#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EFApproaches;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Course/Details.cshtml")]
    public partial class _Views_Course_Details_cshtml : System.Web.Mvc.WebViewPage<EFApproaches.DAL.Entities.Course>
    {
        public _Views_Course_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Course\Details.cshtml"
  
    ViewBag.Title = "Details";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>Details</title>\r\n</head>\r\n<body>\r\n    <div>\r\n        <h4>Course</" +
"h4>\r\n        <hr />\r\n        <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n            <dt>\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Course\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dt>\r\n\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\Course\Details.cshtml"
           Write(Html.DisplayFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n\r\n            <dt>\r\n");

WriteLiteral("                ");

            
            #line 27 "..\..\Views\Course\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Credits));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dt>\r\n\r\n            <dd>\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Course\Details.cshtml"
           Write(Html.DisplayFor(model => model.Credits));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n            <!--Students enrolled list-->\r\n            <dt>\r" +
"\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\Course\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Enrollments));

            
            #line default
            #line hidden
WriteLiteral(" \r\n            </dt>\r\n");

            
            #line 37 "..\..\Views\Course\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Course\Details.cshtml"
             if (Model.Enrollments.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <dd>\r\n                    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                        <tr>\r\n                            <th>Student Name</th" +
">\r\n                            <th>Grade</th>\r\n                        </tr>\r\n");

            
            #line 45 "..\..\Views\Course\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Course\Details.cshtml"
                         foreach (var item in Model.Enrollments)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 49 "..\..\Views\Course\Details.cshtml"
                               Write(Html.DisplayFor(modelItem => item.Student.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 52 "..\..\Views\Course\Details.cshtml"
                               Write(Html.DisplayFor(modelItem => item.Grade));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n");

            
            #line 55 "..\..\Views\Course\Details.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </table>\r\n                </dd>\r\n");

WriteLiteral("                <b> Minimum amount of students in order for the Course to stay op" +
"en:</b>");

WriteLiteral("<span");

WriteLiteral(" id=\"minimumReqMsgContainer\"");

WriteLiteral("> ");

            
            #line 58 "..\..\Views\Course\Details.cshtml"
                                                                                                                      Write(ViewBag.MinimumStudentsToStayOpen);

            
            #line default
            #line hidden
WriteLiteral("</span>");

WriteLiteral("<br />\r\n");

WriteLiteral("                <span><b> Students:</b> ");

            
            #line 59 "..\..\Views\Course\Details.cshtml"
                                   Write(Model.Enrollments.Count());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                <br />\r\n");

            
            #line 61 "..\..\Views\Course\Details.cshtml"
                if (Model.Enrollments.Count >= ViewBag.MinimumStudentsToStayOpen)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" style=\"color:green\"");

WriteLiteral(" id=\"MinimumStudentsMessageContainer\"");

WriteLiteral("> THE MINIMUM AMOUNT IS COMPLIED </span>\r\n");

            
            #line 64 "..\..\Views\Course\Details.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(" id=\"NotMinimumStudentsMessageContainer\"");

WriteLiteral("> THE MINIMUM AMOUNT IS NOT COMPLIED </span>\r\n");

            
            #line 68 "..\..\Views\Course\Details.cshtml"
                }
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <span>: There are no students enrolled in this course</span>\r\n");

            
            #line 73 "..\..\Views\Course\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dl>\r\n    </div>\r\n    <p>\r\n");

WriteLiteral("        ");

            
            #line 78 "..\..\Views\Course\Details.cshtml"
   Write(Html.ActionLink("Edit", "Edit", new { id = Model.CourseID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("        ");

            
            #line 79 "..\..\Views\Course\Details.cshtml"
   Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
