#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EFApproaches;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Teacher/Index.cshtml")]
    public partial class _Views_Teacher_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<EFApproaches.DAL.Entities.Teacher>>
    {
        public _Views_Teacher_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Teacher\Index.cshtml"
  
    ViewBag.Title = "List of Teachers";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n<span");

WriteLiteral(" id=\"viewBagMsgContainer\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Teacher\Index.cshtml"
                          Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Teacher\Index.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.FirstMidName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.EmailAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 33 "..\..\Views\Teacher\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"firstNameValue\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Teacher\Index.cshtml"
                                    Write(item.FirstMidName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"lastNameValue\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Teacher\Index.cshtml"
                                   Write(item.LastName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"titleValue\"");

WriteLiteral(">");

            
            #line 42 "..\..\Views\Teacher\Index.cshtml"
                                Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"emailAddressValue\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Teacher\Index.cshtml"
                                       Write(item.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"fullNameValue\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\Teacher\Index.cshtml"
                                   Write(item.FullName);

            
            #line default
            #line hidden
WriteLiteral("</span>  \r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Edit", "Edit", new { id=item.ID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Details", "Details", new { id=item.ID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Delete", "Delete", new { id=item.ID }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 56 "..\..\Views\Teacher\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<div>\r\n    Full time teachers:<span>");

            
            #line 59 "..\..\Views\Teacher\Index.cshtml"
                        Write(ViewBag.FullTimeTeachers);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n    Part time teachers:<span></span> ");

            
            #line 60 "..\..\Views\Teacher\Index.cshtml"
                                Write(ViewBag.PartTimeTeachers);

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
