#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EFApproaches;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Teacher/Index.cshtml")]
    public partial class _Views_Teacher_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<EFApproaches.DAL.Entities.Teacher>>
    {
        public _Views_Teacher_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Teacher\Index.cshtml"
  
    ViewBag.Title = "List of Teachers";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n<span");

WriteLiteral(" id=\"viewBagMsgContainer\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Teacher\Index.cshtml"
                          Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Teacher\Index.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.EmailAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.HoursPerWeek));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 30 "..\..\Views\Teacher\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"fullNameValue\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Teacher\Index.cshtml"
                                   Write(item.FullName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"titleValue\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Teacher\Index.cshtml"
                                Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"emailAddressValue\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Teacher\Index.cshtml"
                                       Write(item.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n            <span");

WriteLiteral(" class=\"emailAddressValue\"");

WriteLiteral(">");

            
            #line 42 "..\..\Views\Teacher\Index.cshtml"
                                       Write(item.HoursPerWeek);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "editTeacher" }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "detailsTeacher" }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 47 "..\..\Views\Teacher\Index.cshtml"
       Write(Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "deleteTeacher" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 50 "..\..\Views\Teacher\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<div>\r\n    <b>Minimum hours required to be a Full Time teacher:  </b> <" +
"span>");

            
            #line 53 "..\..\Views\Teacher\Index.cshtml"
                                                                Write(ViewBag.MinimumHoursForFullTime);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <br />\r\n    <b>Full time teachers:  </b><span");

WriteLiteral(" id=\"fullTimeTeachersContainer\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\Teacher\Index.cshtml"
                                                                Write(ViewBag.FullTimeTeachers);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    <br />\r\n    <b>Part time teachers:  </b><span");

WriteLiteral(" id=\"partTimeTeachersContainer\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Teacher\Index.cshtml"
                                                                Write(ViewBag.PartTimeTeachers);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
